import esbuild from 'esbuild';
import process from 'process';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD.
The source of this file is the Tablify repository; do not edit main.js by hand.
*/`;

const cssBanner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD.
The source is src/styles/ (tokens.css, brand.css, grid.css, in that order); do not edit styles.css by hand.
*/`;

const production = process.argv[2] === 'production';

const plugin = await esbuild.context({
	banner: { js: banner },
	entryPoints: ['src/plugin/main.ts'],
	bundle: true,
	external: ['obsidian', 'electron', '@codemirror/*', '@lezer/*'],
	format: 'cjs',
	platform: 'browser',
	target: 'es2018',
	// React 19's runtime: JSX compiles to `react/jsx-runtime` imports instead of `React.createElement`,
	// so no file needs `import React`. esbuild's default is the classic runtime, which would fail the
	// build with "React is not defined" the moment a `.tsx` file arrives.
	jsx: 'automatic',
	logLevel: 'info',
	sourcemap: production ? false : 'inline',
	treeShaking: true,
	outfile: 'main.js',
	minify: production,
});

// The stylesheet is bundled, not `@import`ed at runtime: only main.js, manifest.json and styles.css are
// shipped, so an `@import './tokens.css'` in the shipped file would ask the user's install for a file that
// is not there. esbuild resolves the three imports in src/styles/index.css and writes one styles.css.
const styles = await esbuild.context({
	banner: { css: cssBanner },
	entryPoints: ['src/styles/index.css'],
	bundle: true,
	logLevel: 'info',
	sourcemap: production ? false : 'inline',
	outfile: 'styles.css',
	minify: production,
});

if (production) {
	await plugin.rebuild();
	await plugin.dispose();
	await styles.rebuild();
	await styles.dispose();
} else {
	await plugin.watch();
	await styles.watch();
}
