/**
 * The R3 inventory is a fact about the tree, so it is held to the tree.
 *
 * `docs/audit/R3-identity-inventory.md` is generated by `scripts/r3-inventory.ts`, and this file
 * re-runs the same scan and compares the bytes. Three consequences, all of them wanted: the report
 * cannot go stale without a red test; a file that grows a legacy identity marker outside a classified
 * path fails here; and the R1/R2 native path — the document model and the file view — is asserted to
 * carry none of these markers at all, which is the baseline R3 must not break.
 */
import { readFileSync } from 'node:fs';

import { describe, expect, it } from 'vitest';

import {
	MARKERS,
	RULES,
	REPORT_PATH,
	scanInventory,
	renderReport,
} from '../../scripts/r3-inventory';

const inventory = scanInventory();

function report(): string {
	return readFileSync(new URL(`../../${REPORT_PATH}`, import.meta.url), 'utf8');
}

describe('the committed inventory matches the tree', () => {
	it('is byte-identical to a fresh scan', () => {
		expect(report()).toBe(renderReport(inventory));
	});

	it('covers a tree with markers in it, so a green run means something', () => {
		expect(inventory.files.length).toBeGreaterThan(50);
		const occurrences = inventory.files.reduce((sum, file) => sum + file.total, 0);
		expect(occurrences).toBeGreaterThan(500);
	});
});

describe('every marker is classified', () => {
	it('leaves no path with a marker and no rule', () => {
		expect(inventory.uncategorised).toEqual([]);
	});

	it('finds no legacy marker anywhere in the native path', () => {
		// The class `native` exists exactly for this: a match under it is a defect, not a bucket.
		expect(inventory.unclassified).toEqual([]);
	});

	it('uses every class the report documents, and empties only the one R3 step 3 emptied', () => {
		const used = new Set(inventory.files.map((file) => inventory.classOf(file.path)));
		// `host-path` is the one class a step may empty, and step 3 did: `src/adapters/notes/` was its
		// only member, and it matched there through the YAML vocabulary (`toYaml`/`YamlValue`) rather
		// than through a path. When those names went, the class had no members left — which is a fact
		// about the tree, not a hole in the taxonomy: a host-path match is still classified here, and
		// the report's own per-class counts are where emptiness shows up.
		expect([...used].sort()).toEqual(['guard', 'historical', 'remote-record-id', 'replace']);
		expect(inventory.classOf('src/adapters/bases/BasesSource.ts')).toBe('replace');
		expect(inventory.classOf('src/adapters/notes/createNote.ts')).toBe('host-path');
		expect(inventory.classOf('src/sync/pullPush.ts')).toBe('remote-record-id');
		expect(inventory.classOf('tests/fakes/rowSource.ts')).toBe('historical');
		expect(inventory.classOf('tests/unit/view-state.test.ts')).toBe('guard');
		expect(inventory.classOf('tests/unit/value-vocabulary.test.ts')).toBe('guard');
	});

	it('classifies the native path as native, marker-free or not', () => {
		expect(inventory.classOf('src/core/database/envelope.ts')).toBe('native');
		expect(inventory.classOf('src/adapters/tablifyFile/session.ts')).toBe('native');
		expect(inventory.classOf('src/plugin/TablifyFileView.ts')).toBe('native');
		expect(inventory.classOf('src/plugin/viewState.ts')).toBe('native');
	});
});

describe('the rule table itself', () => {
	it('gives every rule a reason a reviewer can weigh', () => {
		for (const rule of RULES) {
			expect(rule.why.length, rule.prefix).toBeGreaterThan(20);
		}
	});

	it('matches on identifiers, never on prose', () => {
		for (const marker of MARKERS) {
			const sample = `const ${marker.name} = 1;`;
			expect(sample, marker.name).toMatch(marker.pattern);
		}
	});
});
